runtime: nodejs16
service: api-gateway
env: standard
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 30m
handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
env_variables:
  PORT: 8080
